import {
  BALL_CONTROL,
  FIELD,
  KEEPER,
  MATCH_TIMING,
  MOVEMENT,
  ORDER_LIFETIME,
  RESTART_RULES,
  TACKLE,
  TICK_RATE,
  ENGINE_VERSION,
  REFEREE,
} from '../sim/rules.ts';
import { PROTOCOL_LIMITS } from './schema.ts';

export function rulebook(): string {
  return `Control one 11-player football team and try to win. Return only requested JSON. intent is a brief public tactical note, not hidden reasoning. memory is a small structured plan returned next time; neither executes actions.
RULESET ${ENGINE_VERSION}, protocol 1. Coordinates are absolute metres: x=0 left goal, x=${FIELD.length} right goal; y=0 top touchline, y=${FIELD.width} bottom. Goal centre y=${FIELD.width / 2}, width ${FIELD.goalWidth}, height ${FIELD.goalHeight}. Attack direction +1 means toward x=${FIELD.length}, -1 toward x=0. Ends swap at halftime. Two ${MATCH_TIMING.halfPlayingTicks / TICK_RATE}-second playing halves; setup pauses playing time. Draws stand.

TEAM COORDINATION
Coach the WHOLE team using teammates AND opponents. teamContext lists active players, possession and THIS half's ownGoal/opponentGoal. Shoot toward opponentGoal; a backward teammate pass is different from an own-goal shot.
Give ONE order to EVERY active teammate in teamContext.teammateIds, including the keeper: hold to stay, guard for keeper positioning, move for support/marking. Refresh useful movement; do not repeat an old instantaneous kick/tackle. Intent and memory cannot move players; omitted players stop when orders expire after ${ORDER_LIFETIME.persistentTicks / TICK_RATE}s.
With possession: compare opposing positions/velocities before choosing a receiver, dribble or shot. Match the carrier's kick and ONE different receiver's move to the SAME meeting point, reserved for that receiver. Give others distinct support targets and defensive cover. Compare ball arrival with receiver travel time, including velocity, pace and acceleration. Matching targets alone is insufficient: the receiver must arrive before the ball passes. If late, choose a closer point, slower delivery or wait/carry. A kick target sets direction, not stopping distance; consider interceptions and controllable arrival speed. The passer's supporting run needs a later order.
CARRY, PASS OR SHOOT: canKickNow is permission, not a reason to release. A carrier's move runs WITH the ball; no kick is needed to dribble. Compare open space, passing lanes and shooting position; retain useful carrying moves. After repeated interceptions, change receiver, lane or timing. The keeper may hold while teammates offer a safer outlet.
Without possession: choose ONE presser/collector; others cover lanes, track different opponents or recover goal-side. Use ball velocity to pick a meeting point. Move into tackle range first.
SPACING: maintain width, different support depths and defensive cover. Compare friendly targets: don't crowd the ball/receiver. Prefer 6m support separation where possible; close challenges/runs can be exceptions. nearestTeammate is current spacing, not a destination. Retain useful currentOrder targets. The engine never spreads players for you.
OPPONENT AWARENESS: infer likely runs, pressure and passes from public position, velocity and facing. Update as opponents move; distinguish observed movement from guessed intent. Opponent orders/memory are hidden.

POSITIONAL RESPONSIBILITIES
Own startingPosition links to teamContext.positioning.briefs; memory assignments are temporary jobs. Use THIS half's goals and left/right touchlines. Forward is toward opponentGoal; goal-side is between threat and ownGoal. Keep centre-back/holding-midfield cover: don't advance both centre backs/fullbacks without replacement cover. On loss, one suitable player presses; others recover goal-side. Roles guide responsibility, not abilities or fixed targets. Role swaps need cover; all movement needs orders.

TACTICAL MEMORY
Memory: plan is one objective; ballPlayerId is the carrier/presser/collector or null; pass names its receiver and meeting point or null. assignments gives teammates distinct jobs, threats records observed opponent concerns, and review assesses the previous attempt using this snapshot/events.
Assign every active outfielder except ballPlayerId a distinct job, including the receiver. Order the keeper too: guard positions; kick distributes an owned ball. Reference active players on the correct side; receiver must differ from ballPlayerId. Translate jobs into actual orders with distinct destinations. Keep useful plans, but reassess after turnover, dismissal, restart or end swap; clear stale passes. recentEvents omits repeated block contacts. Compare event ticks with previousDecisionTick; say unresolved without confirming evidence. Review is your assessment, not an engine-certified outcome. Name interacting players in intent.

ACTION READINESS
Read owned actionContext before ordering. Kick/shoot ONLY with canKickNow. For a loose ball, move to receive first. A null reachableTackleTargetId means move/hold, not a speculative tackle. Readiness uses exact unrounded geometry; it promises neither success nor a legal tackle, and opponents may kick first. Adapt to orderFeedback failures since the previous decision. The full public roster remains in players.

ACTION FORMAT AND EXECUTION
Follow the response schema exactly, without extra fields. Move needs target and pace; guard needs target and NEVER pace. Only kick/shoot take speed and loft.
Copy responseIdentity exactly into batch, adding orders; do not increment decisionId. Both teams observe the same frozen boundary and commit simultaneously; response speed gives no advantage. Random state is hidden. Coordinates are rounded to centimetres in observations only.
A move targets one fixed point at pace 0.01..1. Maximum speed ${MOVEMENT.maximumSpeed} m/s, acceleration ${MOVEMENT.acceleration} m/s². Automatic braking stops at the point. Movement does NOT chase balls, mark opponents or invent supporting runs. A carrier dribbles mechanically at its foot. Orders last ${ORDER_LIFETIME.persistentTicks / TICK_RATE}s, unless replaced/completed/cancelled; omitted players continue then decelerate to rest. hold brakes immediately.
A kick or shoot executes once NOW and fails if that player does not own the ball; it is never queued for future possession. Target is a direction point, speed ${BALL_CONTROL.minimumKickSpeed}..${BALL_CONTROL.maximumKickSpeed} m/s, loft 0..${BALL_CONTROL.maximumLoftSpeed} upward m/s (always supply loft=0 for ground). No automatic aiming or guaranteed success. Ground friction ${BALL_CONTROL.groundDeceleration} m/s²; gravity ${BALL_CONTROL.gravity}. Ground reception is automatic within ${BALL_CONTROL.receivingRadius}m, below ${BALL_CONTROL.maximumFootControlHeight}m and at speeds <=${BALL_CONTROL.maximumFootControlSpeed}m/s; faster/higher contacts can rebound. The kicker cannot re-capture for ${BALL_CONTROL.kickerRecaptureDelayTicks / TICK_RATE}s. Players separate on body overlap.
LOFT: this is initial upward speed, not a target height. A ground kick with loft=3 peaks around 0.6m, loft=6 around 2m and loft=8 around 3.4m. A chip can clear a ground interception lane, but the receiver must meet the descending ball and a high shot may clear the crossbar. Choose ground or aerial delivery from the actual situation; neither is required for spectacle.
Dismissed players cannot receive orders, move or touch the ball. A guard order is ONLY for keeper #1: move to its fixed target at pace ${MOVEMENT.guardingPace}, with automatic catching reach ${KEEPER.guardingReach}m up to ${KEEPER.guardingHeight}m high inside its own penalty area (${FIELD.penaltyAreaDepth}m deep, ${FIELD.penaltyAreaWidth}m wide). Guard does not select a position or chase/predict shots. Keeper must be ordered to distribute after catching.
A tackle attempts to take the ball from targetId NOW: opposing carrier must be within ${TACKLE.maximumOpponentDistance}m and ball within ${TACKLE.ballReach}m. Recovery ${TACKLE.recoveryTicks / TICK_RATE}s. No auto chase. Kicks resolve before tackles at a boundary. Do not tackle a distant player; move into range first.

RESTARTS AND REFEREE
Whole-ball crossings determine goals/out. Posts/bar rebound. Throw-in to opponent of last touch; goal-line miss is corner after defender touch, otherwise goal kick. In restart_setup, both teams may move/hold/guard; awarded team may choose one restart_taker. No kicks or tackles in setup. After ${MATCH_TIMING.restartSetupTicks / TICK_RATE}s the referee clears setup orders, places taker and ball, and enforces ${RESTART_RULES.opponentDistance}m opponent separation (${RESTART_RULES.throwInOpponentDistance}m at throws), own halves at kickoff, opponents outside goal-kick penalty area. Kickoff resets formation. In restart_ready only the selected taker can kick/shoot; both teams may issue movement/guard for the resumed play. Taker MUST kick within ${MATCH_TIMING.restartDeliveryTicks / TICK_RATE}s or match is abandoned. A throw uses kick, speed capped at ${RESTART_RULES.maximumThrowSpeed}, release height ${RESTART_RULES.throwReleaseHeight}. No direct throw-in goal, direct own-restart goal, or consecutive taker touches. Halftime/full_time accept no actions. Phase changes clear old orders.
REFEREE: A tackle reaching through the carrier's body before the ball is a careless foul. Closing speed >=${REFEREE.recklessClosingSpeed} m/s is reckless (yellow), >=${REFEREE.excessiveClosingSpeed} m/s is excessive (red), even when reaching the ball. Two yellows dismiss; fewer than ${REFEREE.minimumPlayers} active players abandons the match. No advantage, automatic replacement keeper or other card offences. Contact location inside the offender's penalty area awards a penalty; otherwise a direct free kick. Penalty spot is ${FIELD.penaltySpotDistance}m from goal: taker must kick forward, opposing keeper starts on the goal line, others behind and outside the area at least ${RESTART_RULES.opponentDistance}m away. A backward penalty awards an indirect free kick.
OFFSIDE: At each teammate touch, a player centre in the opponent half beyond both the ball and second-last defender (tolerance ${REFEREE.offsideTolerance}m) becomes a candidate. An offence occurs only on touching the ball or winning a tackle, even after returning onside. Mere position, screening and obstructing are not judged. Direct throw-in/corner/goal-kick deliveries are exempt. Opponent controlled reception or deliberate kick resets the snapshot; deflections and guarding saves do not. Offside and a restart taker's second touch award an indirect free kick, which cannot score directly.
Fixed-clock simplification: at exactly ${MATCH_TIMING.halfPlayingTicks / TICK_RATE} playing seconds the half ends after that tick's incidents, including an in-flight penalty or newly awarded restart. No penalty extension. Heading, handball, back-pass and keeper holding limits are not implemented. The engine alone decides success, scores and referee outcomes.
No scripted tactical assistance. Invalid responses get at most one repair against the SAME snapshot; failure uses empty orders (continuation/expiry only) and preserves previous memory. Obey schema length limits, including intent <=${PROTOCOL_LIMITS.intentCharacters} characters.`;
}
