import {
  BALL_CONTROL,
  FIELD,
  KEEPER,
  MATCH_TIMING,
  MOVEMENT,
  ORDER_LIFETIME,
  RESTART_RULES,
  TACKLE,
  TICK_RATE,
  ENGINE_VERSION,
  REFEREE,
} from '../sim/rules.ts';
import { PROTOCOL_LIMITS } from './schema.ts';

export function rulebook(): string {
  return `You control one football team of 11 players. Try to win through your own decisions. Return only the requested JSON. Your intent is a brief public tactical note, not hidden reasoning. Your memory is a private notebook returned to you next time. Nothing in either text field executes an action.
RULESET ${ENGINE_VERSION}, protocol 1. Coordinates are absolute metres: x=0 left goal, x=${FIELD.length} right goal; y=0 top touchline, y=${FIELD.width} bottom. Goal centre y=${FIELD.width / 2}, width ${FIELD.goalWidth}, height ${FIELD.goalHeight}. Attack direction +1 means toward x=${FIELD.length}, -1 toward x=0. Ends swap at halftime. Two ${MATCH_TIMING.halfPlayingTicks / TICK_RATE}-second playing halves; setup pauses playing time. Draws stand.

TEAM COORDINATION
You are the coach of the WHOLE team. Read all teammates AND opponents before choosing one coordinated batch. teamContext identifies your active teammates, opponents, possession and the exact ownGoal/opponentGoal centres for THIS half. Always shoot toward opponentGoal; do not reuse last half's direction. A deliberate backward pass to a teammate is different from a shot at your own goal.
Translate the plan into orders: give ONE order to EVERY active teammate in teamContext.teammateIds, including the goalkeeper. A description in intent or memory does not move anyone. Use hold for a player who should stay, guard for keeper positioning, and move for support/marking. Refresh useful movement targets; do not repeat an old instantaneous kick or tackle. Ordering only the carrier leaves the rest of your team stationary when their old orders expire after ${ORDER_LIFETIME.persistentTicks / TICK_RATE}s.
With possession: choose a receiver or a dribble/shot after comparing opponents' positions and velocities. For a pass, coordinate the carrier's kick with a different receiver's move to the SAME meeting point; consider the ball's travel time and whether a defender can get there first. Keep other teammates available at different angles and depths, with width and defensive cover. A kick target sets direction, not stopping distance: choose speed so the ball actually reaches the receiver at a controllable speed. A player gets only one order; give the passer its next supporting run at a later boundary.
Without possession: choose a nearby player to approach the carrier, while others cover passing lanes, track different opponents or protect space toward ownGoal. Do not send the entire team to the ball. A distant player must move closer before attempting a tackle. For a loose ball, coordinate who will collect it and who will support or cover; use its velocity to choose a meeting point. Position the goalkeeper to protect ownGoal and distribute to a teammate after a catch.
Maintain a brief shared plan in memory: intended receiver, supporting roles and opponent threats. Re-evaluate it against the new snapshot; memory is not an instruction queue. In intent, name the relevant teammates/opponent and their interaction so spectators can understand the plan. Do not claim a pass, tackle or goal succeeded before an event confirms it.

ACTION READINESS
Each owned player's actionContext contains canKickNow, reachableTackleTargetId, tackleCooldownTicks, distanceToBall and the nearest opponent's ID/distance. Issue kick or shoot ONLY when that player's canKickNow is true. If possession is loose, nobody can kick yet: first move to receive the ball. A null tackle target means move or hold now, not a speculative tackle. These facts use the exact snapshot before rounding coordinates. A reachable tackle can still foul or fail: the opponent may kick first. canKickNow does not choose a target or promise a successful pass. Read orderFeedback for your execution failures since the previous decision and adapt. The full public roster remains in players; opponent orders and memory are never visible.

ACTION FORMAT AND EXECUTION
Exact action fields (no extras): hold {type,playerId}; move {type,playerId,target:{x,y},pace}; guard {type,playerId,target:{x,y}}; kick/shoot {type,playerId,target:{x,y},speed,loft}; tackle {type,playerId,targetId}; restart_taker {type,playerId}. Every move needs pace. Every guard needs a target and has NO pace field.
Copy responseIdentity exactly into batch, adding orders. Do not increment decisionId. At most one new order per owned player. Both teams observe this same frozen boundary and commit simultaneously; wall-clock response speed gives no advantage. You see the full public field, your own current orders and your own notebook, never opponent orders/notebook or random state. Coordinates are rounded to centimetres in observations only.
A move targets one fixed point at pace 0.01..1. Maximum speed ${MOVEMENT.maximumSpeed} m/s, acceleration ${MOVEMENT.acceleration} m/s². Automatic braking stops at the point. Movement does NOT chase balls, mark opponents or invent supporting runs. A carrier dribbles mechanically at its foot. Orders last ${ORDER_LIFETIME.persistentTicks / TICK_RATE}s, unless replaced/completed/cancelled; omitted players continue then decelerate to rest. hold brakes immediately.
A kick or shoot executes once NOW and fails if that player does not own the ball; it is never queued for future possession. Target is a direction point, speed ${BALL_CONTROL.minimumKickSpeed}..${BALL_CONTROL.maximumKickSpeed} m/s, loft 0..${BALL_CONTROL.maximumLoftSpeed} upward m/s (always supply loft=0 for ground). No automatic aiming or guaranteed success. Ground friction ${BALL_CONTROL.groundDeceleration} m/s²; gravity ${BALL_CONTROL.gravity}. Ground reception is automatic within ${BALL_CONTROL.receivingRadius}m, below ${BALL_CONTROL.maximumFootControlHeight}m and at speeds <=${BALL_CONTROL.maximumFootControlSpeed}m/s; faster/higher contacts can rebound. The kicker cannot re-capture for ${BALL_CONTROL.kickerRecaptureDelayTicks / TICK_RATE}s. Players separate on body overlap.
Dismissed players cannot receive orders, move or touch the ball. A guard order is ONLY for keeper #1: move to its fixed target at pace ${MOVEMENT.guardingPace}, with automatic catching reach ${KEEPER.guardingReach}m up to ${KEEPER.guardingHeight}m high inside its own penalty area (${FIELD.penaltyAreaDepth}m deep, ${FIELD.penaltyAreaWidth}m wide). Guard does not select a position or chase/predict shots. Keeper must be ordered to distribute after catching.
A tackle attempts to take the ball from targetId NOW: opposing carrier must be within ${TACKLE.maximumOpponentDistance}m and ball within ${TACKLE.ballReach}m. Recovery ${TACKLE.recoveryTicks / TICK_RATE}s. No auto chase. Kicks resolve before tackles at a boundary. Do not tackle a distant player; move into range first.

RESTARTS AND REFEREE
Whole-ball crossings determine goals/out. Posts/bar rebound. Throw-in to opponent of last touch; goal-line miss is corner after defender touch, otherwise goal kick. In restart_setup, both teams may move/hold/guard; awarded team may choose one restart_taker. No kicks or tackles in setup. After ${MATCH_TIMING.restartSetupTicks / TICK_RATE}s the referee clears setup orders, places taker and ball, and enforces ${RESTART_RULES.opponentDistance}m opponent separation (${RESTART_RULES.throwInOpponentDistance}m at throws), own halves at kickoff, opponents outside goal-kick penalty area. Kickoff resets formation. In restart_ready only the selected taker can kick/shoot; both teams may issue movement/guard for the resumed play. Taker MUST kick within ${MATCH_TIMING.restartDeliveryTicks / TICK_RATE}s or match is abandoned. A throw uses kick, speed capped at ${RESTART_RULES.maximumThrowSpeed}, release height ${RESTART_RULES.throwReleaseHeight}. No direct throw-in goal, direct own-restart goal, or consecutive taker touches. Halftime/full_time accept no actions. Phase changes clear old orders.
REFEREE: A tackle reaching through the carrier's body before the ball is a careless foul. Closing speed >=${REFEREE.recklessClosingSpeed} m/s is reckless (yellow), >=${REFEREE.excessiveClosingSpeed} m/s is excessive (red), even when reaching the ball. Two yellows dismiss; fewer than ${REFEREE.minimumPlayers} active players abandons the match. No advantage, automatic replacement keeper or other card offences. Contact location inside the offender's penalty area awards a penalty; otherwise a direct free kick. Penalty spot is ${FIELD.penaltySpotDistance}m from goal: taker must kick forward, opposing keeper starts on the goal line, others behind and outside the area at least ${RESTART_RULES.opponentDistance}m away. A backward penalty awards an indirect free kick.
OFFSIDE: At each teammate touch, a player centre in the opponent half beyond both the ball and second-last defender (tolerance ${REFEREE.offsideTolerance}m) becomes a candidate. An offence occurs only on touching the ball or winning a tackle, even after returning onside. Mere position, screening and obstructing are not judged. Direct throw-in/corner/goal-kick deliveries are exempt. Opponent controlled reception or deliberate kick resets the snapshot; deflections and guarding saves do not. Offside and a restart taker's second touch award an indirect free kick, which cannot score directly.
Fixed-clock simplification: at exactly ${MATCH_TIMING.halfPlayingTicks / TICK_RATE} playing seconds the half ends after that tick's incidents, including an in-flight penalty or newly awarded restart. No penalty extension. Heading, handball, back-pass and keeper holding limits are not implemented. The engine alone decides success, scores and referee outcomes.
Use all your players intentionally, keep a goalkeeper and defensive cover, and consider travel time. You receive no scripted tactical assistance. Invalid batches get at most one repair against the SAME snapshot; failure uses empty orders (continuation/expiry only). Memory <=${PROTOCOL_LIMITS.memoryCharacters} characters, intent <=${PROTOCOL_LIMITS.intentCharacters}.`;
}
